name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # change to 'master' if your repo uses master

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # this uploads the root folder (where index.html is)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
